name: authentication
description: "Movie App with authentication"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # Network
  http: ^1.2.2
  
  # Model Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # State management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4



dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  flutter_test:
    sdk: flutter
  

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
